### ISSUE TITLE
Video page

### ISSUE THREAD

**Issue by newick** [betagouv/ClasseA12#15]
- [x] change order to display title first
- [x] improves commentary and ressources display
- [x] check contributions list
- [x] check contribution form
- [x] design and edit actions under the video when logged in
- [x] display resource size
- [x] style the resource size and mimetype
- [x] display resource uploader
- [x] add tchap sharing link
- [x] improves date display for contributions
- [x] on suggestion part, a button "see more" is designed, easy to implement?
- [x] hide resources part if empty
- [x] style the "Partager la vidéo en utilisant une application" share button (also present below the news detail page): it's currently a missing icon at `%PUBLIC_URL%/images/icons/32x32/app_32_purple.svg`
- [x] hide description part if empty. And the best would be to hide `video_infos` if description and resources are empty

**Comment by newick** [comment]
@magopian aside the design line, I think the rest is for you. If you need to talk about it, you know where to find me :)

**Comment by magopian** [comment]
Hi @newick I believe i'm now done on this issue!

**Comment by newick** [comment]
@magopian the actions under the video are designed to be 
![image](https://user-images.githubusercontent.com/657454/134175432-c5fb1508-614c-40cd-8f77-7263f19ea4c2.png)

I managed to add icon to the "télécharger" but "Ajouter/retirer des favoris" is a `Components.button`, I don't know how to manage that.  
What about the "Supprimer la vidéo" ?

**Comment by magopian** [comment]
I created an `Components.iconButton` that acts like a standard `Components.button` with an additional icon, which means it has three states :
- NotLoading (either it already finished loading, or hasn't been requested to load yet)
- Loading (it's requesting some data)
- Disabled (it's not possible to click this button anymore)

So "supprimer cette vidéo" is a standard button (I added an icon in front of it) that opens a confirmation modal, and "ajouter aux favoris", depending on the "favorite status", will have a choice of two icons and texts ("ajouter aux favoris" or "retirer des favoris"), each of them with three states.

What do you think, is that what you needed?

**Comment by magopian** [comment]
Hi @newick I believe I'm done on this one, let me know if you need anything else ;)
