### ISSUE TITLE
Page with sidebar

### ISSUE THREAD

**Issue by newick** [betagouv/ClasseA12#31]
Currently the sidebar changes to a select menu which is perfect, but when one clicks on a link the page changes without closing the select.
@magopian is it possible to do something more user friendly?

**Comment by newick** [comment]
Currently the sidebar changes to a select menu which is perfect, but when one clicks on a link the page changes without closing the select.
@magopian is it possible to do something more user friendly?

**Comment by magopian** [comment]
@newick we need to discuss this: at the moment there's already a "mobile only" menu (with an opener behind the `mobile-only logo` link at the top of the page).
I'm not sure if this menu is still relevant? (it's the `aside class="mobile-menu"` that seems to have all the content of the side bar).

And now I'm also seeing the `details class="mobile-only mobile-categories"` that seems to serve roughly the same purpose (but without the search bar, and only on the "all videos" page?).

In any case it's possible to track the open/close state of the `details` tag, and set it to closed as soon as one of the links is clicked.

**Comment by newick** [comment]
@magopian the trigger is nice but, it should be in the header, with the proper content.
This content could be after it has been moved.

**Comment by magopian** [comment]
@newick this is now done ;) Let me know if it needs any more work!
