### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by newick** [betagouv/ClasseA12#32]
Previous behavior was to use sidebar content as the nav. We could remove it but I think we could reuse some bits.
@magopian could you do something to display a mobile menu but with a button in the header?

Not sure if i'm clear, we could speak about it whenever you want.

**Comment by magopian** [comment]
yeah we need to discuss this, I'm not sure I understand what you want on this one.
Probably related to https://github.com/betagouv/ClasseA12/issues/31#issuecomment-963278406

**Comment by newick** [comment]
@magopian i've just pushed mobile nav design.
Could you trigger it to open it and add code to close it.
It needs the same `is-blocked` class as in https://github.com/betagouv/ClasseA12/issues/7#issuecomment-985372611

We can talk about it whenever you need.

**Comment by magopian** [comment]
> @magopian i've just pushed mobile nav design. Could you trigger it to open it and add code to close it.

This is now done and should be working as expected.


> It needs the same `is-blocked` class as in [#7 (comment)](https://github.com/betagouv/ClasseA12/issues/7#issuecomment-985372611)

Tracking this in #7
