### ISSUE TITLE
[Navigation] Passage de la liste de vidéos à une vidéo garde le scroll

### ISSUE THREAD

**Issue by newick** [betagouv/ClasseA12#43]
@magopian si je suis en bas d'une liste de vidéos et que je clique sur une vidéo, je me retrouve en bas de la page de cette vidéo.

Tu pourrais regarder ?

**Comment by magopian** [comment]
Je voulais faire ça depuis longtemps, je viens de le rajouter dans 3304ef731a6083a159ef00b343d156e39dfffc4c
