### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by newick** [betagouv/ClasseA12#7]
- [x] move logo to the top
- [x] add navigation
- [x] move search bar
- [x] display search bar
- [x] move "add video" button
- [x] move login button

**Comment by newick** [comment]
need some design feedback from Aymeric for the search bar.

@magopian could you manage the navigation with the new pages?

**Comment by newick** [comment]
@magopian if the Users are in any subpages of one of the 3 main pages (Videos, Actus, À propos) the item in the header nav need to stay active.

**Comment by magopian** [comment]
> @magopian if the Users are in any subpages of one of the 3 main pages (Videos, Actus, À propos) the item in the header nav need to stay active.

This is now done

**Comment by newick** [comment]
@magopian I just pushed search form in header.
Could you do that the magnifier button opens and closes the div with the field and search button? 🙇

**Comment by magopian** [comment]
Hi @newick, I did it only for the desktop version, do you want the same on the mobile version? I'm not sure where the search form is located on the mobile version, nor how it behaves?

**Comment by newick** [comment]
@magopian is it possible to display the "publier une vidéo" button only when logged in?

**Comment by newick** [comment]
@magopian for the search part, the design part is done.
Could you add a `.is-blocked` class on the `<body>` to block overflow ?
And make the "fermer" button close the div and remove the `is-blocked` class ?

**Comment by magopian** [comment]
@newick ça marche je te fais ça la semaine prochaine je pense 👍

**Comment by magopian** [comment]
> @magopian for the search part, the design part is done. Could you add a `.is-blocked` class on the `<body>` to block overflow ? And make the "fermer" button close the div and remove the `is-blocked` class ?

This should be done both for the search "modal" and for the mobile menu

**Comment by magopian** [comment]
@newick i pushed some changes to apply this `is-blocked` class to a `body-wrapper` div just inside the `body`. It doesn't seem to prevent the scrollbar from displaying, not sure if there's a way to fix that?

**Comment by magopian** [comment]
@newick regarding the "mobile menu nav links", I've added them, but they need styling:

<img width="435" alt="Capture d’écran 2021-12-06 à 18 04 34" src="https://user-images.githubusercontent.com/167767/144889679-8df6131e-2199-4eed-9bd1-54fad9c12354.png">
