### ISSUE TITLE
Aside 

### ISSUE THREAD

**Issue by newick** [betagouv/ClasseA12#8]
- [x] change design
- [x] change content
- [x] add logo "école de la confiance"
- [x] change lab110bis logo

**Comment by newick** [comment]
@magopian 
we'll need a way to separate aside for video pages, news pages and content pages

![image](https://user-images.githubusercontent.com/657454/130447284-463cdb53-efd2-4ed7-99ee-87365865ef5b.png)
![image](https://user-images.githubusercontent.com/657454/130447308-9ee2a107-5694-4b9e-bd28-406f46889666.png)
![image](https://user-images.githubusercontent.com/657454/130447335-eeadbb82-81d3-4250-9ec0-e2ab0f8e56d5.png)

**Comment by newick** [comment]
oups didn't send it :/

We'd need ecole de la confiance logo in SVG

**Comment by magopian** [comment]
No need for a link on the "école de la confiance" logo 👍
